// GENERATED from https://asf.org.au/grant-agreement (ASF grant agreement,
// school <-> ASF). Verbatim. Do not hand-edit; re-generate from source.
export const GRANT_HTML = `<h2>Recitals</h2>
<ol><li>Australian Sports Foundation Limited (ACN 008 613 858) (ASF) is a company established by the Australian Government for the purpose of raising money to develop sport in Australia.</li><li>In pursuit of its purposes, ASF provides financial assistance to organisations, qualifying athletes, coaches, officials and other support staff consistent with the purposes of ASF.</li><li>ASF Community Sports Fund Pty Ltd (ACN 619 867 855) as trustee for Australian Sports Foundation Charitable Fund (ABN 97 179 064 897) (ASFCF) is a charitable trust that seeks to support the development of sport in Australia for one or more charitable purposes.</li><li>ASFCF receives funds from a range of sources, including but not limited to private ancillary funds, charitable trusts, and private and corporate donors. These funds are to be used by ASFCF for its charitable purposes.</li><li>Together, ASF and ASFCF are referred to as the ‘ASF Group’.</li><li>The Grant Recipient has submitted an application to the ASF Group for financial assistance.</li><li>The ASF Group agrees to provide financial assistance to the Grant Recipient in accordance with the terms and conditions set out in this Agreement, as amended by the ASF Group at its discretion from time to time.</li><li>It is the expectation of the ASF Group that the financial assistance will be used by the Grant Recipient for the Campaign, within the overall purpose of supporting the development of sport in Australia, and, in the case of Grants from ASFCF, for one or more charitable purposes.</li></ol>
<h2>Operative Provisions</h2>
<h3>1 Definitions and interpretations</h3>
<h4>1.1 Definitions</h4>
<p>The following words have these meanings in this Agreement unless the contrary intention appears:</p>
<p>Agreement means this agreement, including any schedule, annexure and attachments.</p>
<p>Application means the online sign up form as amended or updated from time to time, accessed and submitted to the ASF Group by the Grant Recipient on the Website.</p>
<p>Campaign means the purpose or activity of the Grant Recipient in respect of which the Grant Recipient seeks to receive a Grant, or as otherwise agreed between the parties in writing.</p>
<p>Corporations Act means the Corporations Act 2001 (Cth).</p>
<p>Grant means any of the funds, property or other support provided under clause 3.</p>
<p>Grant Impact Report means a report that must be submitted in accordance with clause 5.1 of this Agreement.</p>
<p>Grant Recipient means the person named in the Application approved by the ASF Group.</p>
<p>Grantor means the entity in the ASF Group which is to provide the Grant under this Agreement in accordance with clause 3.1(a) of this Agreement.</p>
<p>GST has the same meaning as in the GST Act.</p>
<p>GST Act means the A New Tax System (Goods and Services Tax) Act 1999 (Cth).</p>
<p>Personal Information has the meaning given to the term in the Privacy Act 1988 (Cth) from time to time.</p>
<p>Personnel includes the employees, staff (whether paid or unpaid) and volunteers of the Grant Recipient or ASF Group, as the context requires.</p>
<p>Website means the website(s) of the ASF Group.</p>
<h4>1.2 Interpretation</h4>
<p>In the Agreement unless the contrary intention appears:</p>
<ol><li>a reference to this Agreement or another instrument includes any variation or replacement of either of them;</li><li>a reference to a statute, ordinance, code or other law includes regulations and other instruments under it and consolidations, amendments, re-enactments or replacements of any of them;</li><li>the singular includes the plural and vice versa;</li><li>the word “person” includes a firm, a body corporate, an unincorporated association or an authority;</li><li>a reference to a person includes a reference to the person’s executors, administrators, successors, substitutes (including, but not limited to, persons taking by novation) and assigns;</li><li>an agreement, representation or warranty on the part of or in favour of two or more persons binds or is for the benefit of them jointly and severally;</li><li>if a period of time is specified and dates from a given day or the day of an act or event, it is to be calculated exclusive of that day; and</li><li>a reference to a day is to be interpreted as the period of time commencing at midnight and ending 24 hours later.</li></ol>
<h3>2 Campaigns</h3>
<h4>2.1 Application for approval of Campaigns</h4>
<p>The Grant Recipient has submitted its Campaign/s to the ASF Group for approval or amendment, in such a form as determined by the ASF Group from time to time.</p>
<h3>3 Grants</h3>
<h4>3.1 Awards of Grants</h4>
<ol><li>Subject to the availability of funds and resources, and in its sole discretion, the ASF Group agrees to provide a Grant to the Grant Recipient for a Campaign.</li><li>In its sole discretion, the ASF Group will determine which of the entities in the ASF Group is to be the Grantor in respect of the Campaign.</li></ol>
<h4>3.2 Donor preferences and other conditions</h4>
<ol><li>The Grant Recipient acknowledges that each Grant is made in the sole discretion of the ASF Group and nothing in this Agreement limits the discretion of the ASF Group in respect of a Grant to the Grant Recipient whatsoever.</li><li>In making Grants, the ASF Group may give consideration to preferences expressed by donors in making donations to ASF Group in respect of preferences for the Campaign.</li></ol>
<h4>3.3 Payment and bank account</h4>
<p>The Grantor will pay any Grant funds to the Grant Recipient by direct transfer to the bank account of the Grant Recipient stated in the application or such other bank account as notified by the Grant Recipient to the ASF Group within a reasonable period before the payment is due.</p>
<h3>4 Obligations of the Grant Recipient</h3>
<h4>4.1 Use of Grant</h4>
<p>The Grant Recipient represents that it will:</p>
<ol><li>use each Grant solely for the Campaign;</li><li>use each Grant solely in accordance with the description set out in the application for the Campaign for which the Grant is provided;</li><li>make best endeavours to achieve the desired outcomes and indicators of each Campaign; and</li><li>ensure that any information provided to the ASF Group is true and accurate in all material respects.</li></ol>
<h4>4.2 Reputation of the ASF Group</h4>
<p>The Grant Recipient must not do, or cause to be done, or allow to be done, anything within the Grant Recipient’s reasonable control, that may harm or result in detriment to the good name and reputation of the ASF Group or may adversely affect, reflect or impact on the ASF Group.</p>
<h4>4.3 Record keeping</h4>
<p>The Grant Recipient will:</p>
<ol><li>maintain accurate financial records, in accordance with applicable accounting standards, in relation to the use of each Grant (including a record of amounts and items received and expended); and</li><li>maintain financial and operational records relating to each Campaign for a minimum of 7 years from the termination of this Agreement, and make such records available to the ASF Group (or any of its representatives including auditors) during that time as reasonably required by the ASF Group.</li></ol>
<h4>4.4 Refunds in exceptional circumstances</h4>
<p>The Grant Recipient acknowledges that, in exceptional circumstances (including where the Grant has been affected by a mistake), the ASF Group may in its absolute discretion issue a notice to the Grant Recipient requesting that the Grant be repaid, in whole or in part, to the Grantor, and that the Grant Recipient must promptly, and within 14 days, repay the Grant to the Grantor.</p>
<h3>5 Reporting to the ASF Group</h3>
<h4>5.1 Grant Impact Report</h4>
<p>The Grant Recipient will provide to the ASF Group a Grant Impact Report containing information specified by ASF Group on the use and impact of each Grant provided to the Grant Recipient at such times and in such manner as may be requested from time to time by the ASF Group.</p>
<h4>5.2 Reviews, monitoring and evaluation</h4>
<ol><li>The ASF Group may at any time conduct a review of the Grant Recipient or a Campaign for such purposes as it thinks fit, including to ensure that the Grant is used solely for the Campaign and in accordance with the terms of this Agreement.</li><li>The Grant Recipient must:</li><li>provide all information reasonably requested by the ASF Group for the purpose of reviewing, monitoring and evaluating each Campaign;</li><li>permit a Campaign to be inspected by the ASF Group, or its representatives, on request; and</li><li>attend meetings as requested by the ASF Group.</li></ol>
<h4>5.3 Notification obligations</h4>
<ol><li>The Grant Recipient must promptly and within 14 days notify the ASF Group of any changes or proposed changes to: the information provided to the ASF Group or details of a Campaign (including information in reports and any material changes to the Campaign); or the authorised contact or the contact details provided under this Agreement.</li><li>the information provided to the ASF Group or details of a Campaign (including information in reports and any material changes to the Campaign); or</li><li>the authorised contact or the contact details provided under this Agreement.</li><li>The Grant Recipient must immediately notify the ASF Group in writing of any incident or circumstances: involving a breach or a potential breach of this Agreement; in the nature of an emergency affecting any Campaign; that may have any impact on the good name and reputation of the ASF Group; and which would, or would likely, have a material impact on the desired outcomes and indicators of any Campaign.</li><li>involving a breach or a potential breach of this Agreement;</li><li>in the nature of an emergency affecting any Campaign;</li><li>that may have any impact on the good name and reputation of the ASF Group; and</li><li>which would, or would likely, have a material impact on the desired outcomes and indicators of any Campaign.</li></ol>
<p>The Grant Recipient must promptly and within 14 days notify the ASF Group of any changes or proposed changes to:</p>
<p>The Grant Recipient must immediately notify the ASF Group in writing of any incident or circumstances:</p>
<h3>6 Communications</h3>
<h4>6.1 ASF Group promotional activities</h4>
<p>To enable the ASF Group to raise funds through public and corporate donations, the Grant Recipient acknowledges and agrees that the ASF Group may, in its sole discretion:</p>
<ol><li>promote the relevant Campaign using copies of any promotional images and video provided to the ASF Group by the Grant Recipient (and that the Grant Recipient must ensure that any relevant consents have been obtained in relation to any persons who may appear in such images);</li><li>establish a page on the website of ASF Group to showcase the relevant Campaign to donors and potential donors;</li><li>establish an online donation facility for the relevant Campaign;</li><li>generate relevant information in respect of donations received to enable the Grant Recipient to acknowledge or thank donors directly;</li><li>promote the Campaign by such means as the ASF Group in its sole discretion from time to time determines, including references or features on its website, e-newsletters and social media platforms; and</li><li>promote the Campaign and any Grants issued to the Grant Recipient to the general community via any or all relevant media channels.</li></ol>
<h4>6.2 Grant Recipient acknowledgement of the ASF Group</h4>
<ol><li>If the Grant Recipient chooses to acknowledge the financial assistance provided by the ASF Group, the ASF Group requests that it does so using the Acknowledgement Guidelines set out at Schedule 1.</li><li>The Grant Recipient must amend or remove any reference to the ASF Group, its logo, or any description of the Grant or Campaign if requested to do so by the ASF Group.</li><li>The Grant Recipient must not use the ASF Group’s logo or marks other than in accordance with the Acknowledgement Guidelines set out at Schedule 1 without the prior written approval of the ASF Group.</li></ol>
<h3>7 Intellectual Property</h3>
<p>The Grant Recipient will own all industrial and intellectual property rights created by the Grant Recipient in carrying out each Campaign.</p>
<h3>8 Tax obligations</h3>
<p>The Grant Recipient acknowledges that:</p>
<ol><li>the ASF Group is not authorised to provide taxation advice and provides no warranties or representations as to the tax law;</li><li>the Grant Recipient will not misrepresent matters relating to tax law including in relation to tax deductions for donations;</li><li>the Grant Recipient is solely responsible for ensuring that it complies with any obligations in respect of tax law which apply to the Grant Recipient.</li></ol>
<h3>9 GST</h3>
<ol><li>The Grantor intends that Grants made under this Agreement are a “financial assistance payment” within the meaning of GSTR 2012/2. Specifically, the Grantor does not intend that Grants are consideration for any supply. Accordingly, unless otherwise expressly stated, all amounts and sums payable is expressed to be exclusive of goods and services tax under the GST Act.</li><li>In the event that GST is subsequently found to apply to any Grants made under this Agreement, the Grant Recipient agrees to issue to the Grantor a tax invoice for the relevant amount and the Grantor will remit GST due to the Grant Recipient.</li></ol>
<h3>10 Repayment of Grant on material breach</h3>
<ol><li>For the purposes of this clause 10, each of the following constitutes a breach of a material term of this Agreement, if, in the opinion of the ASF Group: any Grant funds have been used by the Grant Recipient for a purpose other than that which is within the overall purpose of supporting the development of sport in Australia, and, in the case of Grants from ASFCF, for one or more charitable purposes; the ASF Group’s name, standing and reputation is brought into disrepute by the Grant Recipient or by being associated with the Grant Recipient or as a result of any restructure or controversy affecting the Grant Recipient; or a material representation provided by the Grant Recipient under this Agreement is inaccurate, incomplete, or otherwise misleading.</li><li>any Grant funds have been used by the Grant Recipient for a purpose other than that which is within the overall purpose of supporting the development of sport in Australia, and, in the case of Grants from ASFCF, for one or more charitable purposes;</li><li>the ASF Group’s name, standing and reputation is brought into disrepute by the Grant Recipient or by being associated with the Grant Recipient or as a result of any restructure or controversy affecting the Grant Recipient; or</li><li>a material representation provided by the Grant Recipient under this Agreement is inaccurate, incomplete, or otherwise misleading.</li><li>The Grant Recipient must repay Grants for one or more Campaigns to the Grantor in whole or in part on demand if the ASF Group determines that the Grant Recipient has breached a material term of this Agreement, unless otherwise agreed to in writing by the ASF Group.</li><li>If the breach is capable of being remedied, the Grant Recipient has 21 days, upon receipt of notice of the breach from the ASF Group (or within any longer period specified in the notice) to remedy the breach or otherwise the Grant Recipient must repay the Grants to the ASF Group in whole or in part and for one or more Campaigns as may be determined by the ASF Group, on demand, as set out at clause 10(a) above.</li></ol>
<p>For the purposes of this clause 10, each of the following constitutes a breach of a material term of this Agreement, if, in the opinion of the ASF Group:</p>
<h3>11 Disclaimer of liability</h3>
<p>The ASF Group is not responsible for and disclaims all liability for any loss or damage suffered by the Grant Recipient or any other person in respect of any Campaigns or this Agreement.</p>
<h3>12 Termination of the Agreement</h3>
<h4>12.1 Termination of the Agreement</h4>
<ol><li>Either party may remove the Campaign at any time.</li><li>The ASF Group may terminate a Grant and therefore the application of this Agreement to a Campaign, in its sole discretion, if: it has insufficient funds for the Grant; or following any review of the Campaign by the ASF Group, it determines that it would be in its best interest to terminate the Agreement.</li><li>it has insufficient funds for the Grant; or</li><li>following any review of the Campaign by the ASF Group, it determines that it would be in its best interest to terminate the Agreement.</li></ol>
<p>The ASF Group may terminate a Grant and therefore the application of this Agreement to a Campaign, in its sole discretion, if:</p>
<h4>12.2 Obligation on termination</h4>
<ol><li>On termination of this Agreement, the Grant Recipient must apply any unspent portion of any Grant: If the Grantor was ASF, for the development of sport; or If the Grantor was ASFCF, for the development of sport which advances a charitable purpose.</li><li>If the Grantor was ASF, for the development of sport; or</li><li>If the Grantor was ASFCF, for the development of sport which advances a charitable purpose.</li><li>If the ASF Group terminates the Agreement for material breach, and in the reasonable opinion of ASF Group, the Grant Recipient has not applied any Grant, in whole or in part, in accordance with the Agreement:</li><li>the ASF Group may issue a notice to the Grant Recipient requesting that the Grant be repaid, in whole or in part, to the Grantor; and</li><li>the Grant Recipient must promptly, and within 14 days, repay the Grant to the Grantor.</li><li>The provisions in clause 5 survive the termination of this Agreement.</li></ol>
<p>On termination of this Agreement, the Grant Recipient must apply any unspent portion of any Grant:</p>
<h3>13 General provisions</h3>
<h4>13.1 Entire Agreement, Variation and waiver</h4>
<ol><li>This Agreement constitutes the entire agreement between the parties and supersedes all prior arrangements with respect to the Grant Recipient.</li><li>This Agreement may be varied only as agreed by the parties in writing from time to time.</li><li>A request to vary this Agreement may be submitted in writing by a party. The party in receipt of the request must promptly review and determine the request.</li><li>A right created under this Agreement may only be waived by a notice in writing by the party granting the waiver.</li></ol>
<h4>13.2 Relationship</h4>
<ol><li>This Agreement does not create a principal-agent, joint venture, partnership, employment or service provider relationship between the parties. Nothing in this Agreement will cause any personnel, agent or subcontractor of one party to be or become a personnel, agent or sub-contractor of the other party.</li><li>The Grant Recipient must not:</li><li>misrepresent its relationship with the ASF Group under this Agreement; or</li><li>attempt to bind or represent the ASF Group in any way.</li></ol>
<h3>14 Notices</h3>
<ol><li>A notice under this Agreement is ineffective unless it is in writing.</li><li>A notice by post or by electronic means, other than through the website of the ASF Group, must be directed as follows:For the ASF Group: Address: PO Box 176 Belconnen ACT 2616 Attention: Chief Executive Officer Email: info@asf.org.au</li></ol>
<p>A notice by post or by electronic means, other than through the website of the ASF Group, must be directed as follows:</p>
<p>For the ASF Group:</p>
<p>Address: PO Box 176 Belconnen ACT 2616 Attention: Chief Executive Officer Email: info@asf.org.au</p>
<ol><li>For the Grant Recipient: to the Grant Recipient, or their authorised contact, and to the postal or electronic address as specified on the Application, or as last notified to the ASF Group in writing.</li><li>Notices delivered by email must include a statement that the communication is a notice under this Agreement.</li></ol>
<h4>14.2 Privacy</h4>
<ol><li>The ASF Group will comply with its privacy policy as published on its website, in relation to any Personal Information that is collected, used or disclosed under this Agreement, as applicable.</li><li>The Grant Recipient will not do anything with Personal Information that will cause the ASF Group to breach its obligations under the Privacy Act 1988 (Cth).</li><li>The Grant Recipient will provide all assistance as required by the ASF Group to assist the ASF Group in complying with its obligations when dealing with Personal Information under this Agreement.</li></ol>
<h4>14.2 Assignment and subcontracting</h4>
<ol><li>The Grant Recipient cannot assign or transfer its rights, benefits or obligations under this Agreement to any third party except: to those (if any) who have been approved in writing by the ASF Group; or with the ASF Group’s prior written consent.</li><li>to those (if any) who have been approved in writing by the ASF Group; or</li><li>with the ASF Group’s prior written consent.</li><li>The Grant Recipient cannot subcontract its obligations under this Agreement without the prior consent of the ASF Group. If the ASF Group provides written consent to sub-contract, the Grant Recipient must ensure that its agreement with the sub-contractor contains terms and conditions consistent with the terms of the Grant so as to ensure the Grant Recipient can comply with the requirements of this Agreement.</li></ol>
<p>The Grant Recipient cannot assign or transfer its rights, benefits or obligations under this Agreement to any third party except:</p>
<h4>14.3 Governing law and jurisdiction</h4>
<p>This Agreement is governed by the law in force in the Australian Capital Territory.</p>
<h4>14.4 Counterparts</h4>
<p>This Agreement may be signed in counterparts and will become effective upon the last party signing a counterpart.</p>
<h2>Schedule 1 – Guidelines for acknowledgment of financial assistance provided by the ASF Group</h2>
<p>Should the Grant Recipient choose to acknowledge the financial assistance provided by ASF Group, we request that you refer to ASF Group as a “fundraising partner”.</p>
<p>All resources for acknowledgment, including key messages, logos and other materials are available on the ASF Group website or through the Fundraising Support Team.</p>
<p>If you wish to reference ASF Group’s assistance in media releases, we request that you notify the ASF Group in advance through the Fundraising Support Team.</p>
<p>If you choose to use social media to acknowledge the financial assistance provided by ASF group you can like, follow and share ASF Group content on:</p>
<p>Facebook: https://www.facebook.com/AustralianSportsFoundation</p>
<p>Twitter: https://twitter.com/AusSportsFdn</p>
<p>Instagram: https://instagram.com/australiansportsfoundation/</p>
<p>LinkedIn: http://www.linkedin.com/company/3802906</p>
<p>Please use the ASF Group profiles @AusSportsFdn – Twitter an @aussportsfdn – Instagram, with hashtags, #australiansportsfoundation and #supportyoursport on relevant updates.</p>`;
