import type { CampaignDetail, CampaignSummary } from "@/lib/types";

/**
 * Mock data for local development before Supabase is connected.
 * Figures and Hart-Sport-style items are realistic for AU schools.
 * The data-access layer (lib/data.ts) reads from here today and is
 * the single place to swap in live Supabase queries later.
 */

function inDays(n: number): string {
  return new Date(Date.now() + n * 86_400_000).toISOString();
}

export const MOCK_CAMPAIGNS: CampaignDetail[] = [
  {
    id: "c_basketball_court",
    status: "live",
    title: "Get our basketball program off the ground",
    summary:
      "Year 5–6 has outgrown two split balls and a bent ring. Help us kit out a full training set.",
    description:
      "Forty kids turn up to lunchtime basketball with two usable balls between them. We're building a proper before-school program but need the basics first: a set of size-6 balls, two portable rings the groundskeeper can wheel onto the court, and a ball cart so nothing walks off. Every item below is priced from the Hart Sport catalogue.",
    funding_goal: 1840,
    amount_raised: 1190,
    deadline: inDays(18),
    item_count: 4,
    cover_image:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=70",
    school: {
      id: "s_brunswick",
      name: "Brunswick East Primary School",
      suburb: "Brunswick East",
      state: "VIC",
      verified: true,
    },
    items: [
      {
        id: "i_ball_set",
        campaign_id: "c_basketball_court",
        hart_product_id: "h_bball6",
        title: "Match basketballs — size 6 (set of 10)",
        description: "Indoor/outdoor composite, the size our 5–6s play with.",
        cost: 39.95,
        quantity_needed: 10,
        created_at: inDays(-12),
        product: {
          id: "h_bball6",
          hart_sku: "BB-COMP-6",
          name: "HART Composite Basketball Size 6",
          category: "Basketball",
          unit_price: 39.95,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 8,
        amount_raised: 319.6,
        category: "Basketball",
      },
      {
        id: "i_rings",
        campaign_id: "c_basketball_court",
        hart_product_id: "h_ring",
        title: "Portable basketball ring (×2)",
        description: "Wheel-out base, height adjustable for junior play.",
        cost: 449,
        quantity_needed: 2,
        created_at: inDays(-12),
        product: {
          id: "h_ring",
          hart_sku: "BB-RING-PORT",
          name: "HART Portable Adjustable Basketball System",
          category: "Basketball",
          unit_price: 449,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 1,
        amount_raised: 449,
        category: "Basketball",
      },
      {
        id: "i_cart",
        campaign_id: "c_basketball_court",
        hart_product_id: "h_cart",
        title: "Lockable ball storage cart",
        description: "Holds 30 balls, locks to the equipment shed.",
        cost: 189,
        quantity_needed: 1,
        created_at: inDays(-12),
        product: {
          id: "h_cart",
          hart_sku: "STOR-CART-30",
          name: "HART Lockable Ball Cart",
          category: "Storage",
          unit_price: 189,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 0,
        amount_raised: 0,
        category: "Storage",
      },
      {
        id: "i_pump",
        campaign_id: "c_basketball_court",
        hart_product_id: "h_pump",
        title: "Floor pump + spare needles",
        description: "Because flat balls end every game early.",
        cost: 24.95,
        quantity_needed: 2,
        created_at: inDays(-12),
        product: {
          id: "h_pump",
          hart_sku: "ACC-PUMP-DUAL",
          name: "HART Dual-Action Floor Pump",
          category: "Accessories",
          unit_price: 24.95,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 2,
        amount_raised: 49.9,
        category: "Accessories",
      },
    ],
  },
  {
    id: "c_netball_posts",
    status: "live",
    title: "New netball posts before finals",
    summary:
      "Our posts are rusted through and failed inspection. The season is at risk without a replacement set.",
    description:
      "We host the district carnival each spring, but our two ring posts rusted at the base and were red-tagged. Without a compliant set we forfeit hosting — and our own teams can't train. We're after a competition-grade pair plus padding to keep younger players safe.",
    funding_goal: 1290,
    amount_raised: 1290,
    deadline: inDays(6),
    item_count: 2,
    cover_image:
      "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?auto=format&fit=crop&w=1200&q=70",
    school: {
      id: "s_redlands",
      name: "Redland Bay State School",
      suburb: "Redland Bay",
      state: "QLD",
      verified: true,
    },
    items: [
      {
        id: "i_posts",
        campaign_id: "c_netball_posts",
        hart_product_id: "h_posts",
        title: "Competition netball posts (pair)",
        description: "Steel, weighted base, regulation 3.05m ring height.",
        cost: 545,
        quantity_needed: 2,
        created_at: inDays(-20),
        product: {
          id: "h_posts",
          hart_sku: "NB-POST-COMP",
          name: "HART Competition Netball Post",
          category: "Netball",
          unit_price: 545,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 2,
        amount_raised: 1090,
        category: "Netball",
      },
      {
        id: "i_padding",
        campaign_id: "c_netball_posts",
        hart_product_id: "h_pad",
        title: "Post padding (pair)",
        description: "Foam wrap to protect players on contact.",
        cost: 100,
        quantity_needed: 2,
        created_at: inDays(-20),
        product: {
          id: "h_pad",
          hart_sku: "NB-PAD-STD",
          name: "HART Netball Post Padding",
          category: "Netball",
          unit_price: 100,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 2,
        amount_raised: 200,
        category: "Netball",
      },
    ],
  },
  {
    id: "c_athletics_kit",
    status: "live",
    title: "Cross-country & athletics starter kit",
    summary:
      "Building a running club for 120 kids — we need timing gear, cones and a long-jump mat.",
    description:
      "Last year's fun run turned into a weekly running club nobody expected. We're now coaching sprints and long jump too, all with a borrowed stopwatch and witches' hats from the car park. A proper kit lets us run safe, measurable sessions and a real school carnival.",
    funding_goal: 980,
    amount_raised: 415,
    deadline: inDays(31),
    item_count: 3,
    cover_image:
      "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=70",
    school: {
      id: "s_kalgoorlie",
      name: "Kalgoorlie Primary School",
      suburb: "Kalgoorlie",
      state: "WA",
      verified: false,
    },
    items: [
      {
        id: "i_cones",
        campaign_id: "c_athletics_kit",
        hart_product_id: "h_cones",
        title: "Marker cone set (×40)",
        description: "Hi-vis, nesting, for drills and lane markers.",
        cost: 59,
        quantity_needed: 2,
        created_at: inDays(-5),
        product: {
          id: "h_cones",
          hart_sku: "ATH-CONE-40",
          name: "HART Marker Cone Set",
          category: "Athletics",
          unit_price: 59,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 2,
        amount_raised: 118,
        category: "Athletics",
      },
      {
        id: "i_timer",
        campaign_id: "c_athletics_kit",
        hart_product_id: "h_timer",
        title: "Digital stopwatch set",
        description: "Six-pack so every house team can time a heat.",
        cost: 119,
        quantity_needed: 1,
        created_at: inDays(-5),
        product: {
          id: "h_timer",
          hart_sku: "ATH-TIMER-6",
          name: "HART Stopwatch 6-Pack",
          category: "Athletics",
          unit_price: 119,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 1,
        amount_raised: 119,
        category: "Athletics",
      },
      {
        id: "i_mat",
        campaign_id: "c_athletics_kit",
        hart_product_id: "h_mat",
        title: "Long-jump landing mat",
        description: "Soft-fall mat so sand pit days aren't the only option.",
        cost: 743,
        quantity_needed: 1,
        created_at: inDays(-5),
        product: {
          id: "h_mat",
          hart_sku: "ATH-LJ-MAT",
          name: "HART Long Jump Landing Mat",
          category: "Athletics",
          unit_price: 743,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 0,
        amount_raised: 0,
        category: "Athletics",
      },
    ],
  },
  {
    id: "c_soccer_goals",
    status: "live",
    title: "Replace the broken soccer goals",
    summary:
      "Both junior goals snapped over winter. Help us get safe, portable replacements for the oval.",
    description:
      "Our two aluminium goals corroded and one frame buckled mid-game — thankfully no one was hurt, but we've taped them off since. We want portable, weighted goals the staff can move off the oval so the cricket pitch survives summer too.",
    funding_goal: 760,
    amount_raised: 240,
    deadline: inDays(12),
    item_count: 2,
    cover_image:
      "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=70",
    school: {
      id: "s_glenorchy",
      name: "Glenorchy Primary School",
      suburb: "Glenorchy",
      state: "TAS",
      verified: true,
    },
    items: [
      {
        id: "i_goals",
        campaign_id: "c_soccer_goals",
        hart_product_id: "h_goal",
        title: "Portable soccer goal (pair)",
        description: "3m × 2m, folding, with weighted anchor bag.",
        cost: 329,
        quantity_needed: 2,
        created_at: inDays(-8),
        product: {
          id: "h_goal",
          hart_sku: "SOC-GOAL-3M",
          name: "HART Portable Folding Soccer Goal 3m",
          category: "Soccer",
          unit_price: 329,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 0,
        amount_raised: 0,
        category: "Soccer",
      },
      {
        id: "i_balls",
        campaign_id: "c_soccer_goals",
        hart_product_id: "h_socball",
        title: "Training soccer balls (set of 12)",
        description: "Size 4 for the junior teams.",
        cost: 25,
        quantity_needed: 4,
        created_at: inDays(-8),
        product: {
          id: "h_socball",
          hart_sku: "SOC-BALL-4",
          name: "HART Training Soccer Ball Size 4",
          category: "Soccer",
          unit_price: 25,
          product_url: "https://hartsport.com.au/your-product-page",
          synced_at: inDays(-1),
        },
        quantity_funded: 4,
        amount_raised: 100,
        category: "Soccer",
      },
    ],
  },
];

export const MOCK_SUMMARIES: CampaignSummary[] = MOCK_CAMPAIGNS.map((c) => ({
  id: c.id,
  title: c.title,
  summary: c.summary,
  status: c.status,
  funding_goal: c.funding_goal,
  amount_raised: c.amount_raised,
  deadline: c.deadline,
  item_count: c.item_count,
  cover_image: c.cover_image,
  school: c.school,
}));
