// GENERATED from https://asf.org.au/terms-and-conditions (ASF donor T&Cs).
// Verbatim except "our website" -> "the Kitup website". Do not hand-edit.
export const TERMS_HTML = `<h3>1. Introduction</h3>
<p>The Australian Sports Foundation Ltd (ABN 27 008 613 858) (ASF) and the Trustee for the Australian Sports Foundation Charitable Fund (ABN 97 179 064 897) (ASFCF) (referred to separately and together in this document as we or us) were established by the Australian Government to raise funds for the development of sport in Australia (and in respect of ASFCF, where that is in in pursuit of a charitable purpose). Our specific listings in the Income Tax Assessment Act 1997 (Cth) (Subdivision 30-B, section 30-90) mean that donations to us of $2 or more are tax deductible, subject to the donor meeting eligibility requirements for claiming the tax deduction.</p>
<p>These Terms and Conditions (T&amp;Cs) govern the relationship between a donor (you) and us. They should be read in conjunction with our Disclaimer and Privacy Policy. Use of the Kitup website signifies acceptance of these T&amp;Cs and our policies, and your awareness of the policies and information specified in these documents.</p>
<h3>2. Donations and tax deductibility</h3>
<p>By making a payment through the Kitup website, you understand and agree that the payment is a voluntary gift by you to us with a preference indicated by you for a particular individual, team or project (Preferred Sporting Cause) that appears on the Kitup website.</p>
<p>All donations made to us are non-refundable and are not subject to GST. For donations of $2 or more, you may be eligible to claim a tax deduction and a receipt will be forwarded to you to the email address provided by you at the time of making the payment.</p>
<p>It is your responsibility to make a claim for the deduction on your tax return, and the onus is on you to assure yourself of your eligibility to claim a deduction for a particular gift to us, as with gifts to any other Deductible Gift Recipient (DGR).</p>
<p>Guidance on tax deductible gifts can be found on the Australian Taxation Office (ATO) website and requirements include that a gift:</p>
<p>• must be voluntary</p>
<p>• must be unconditional</p>
<p>• must not be the result of or made in relation to a contractual obligation or pre-existing agreement including an invoice</p>
<p>You or your associates*(1) must not receive any material benefit in connection with the making of a donation. Please refer to Information for Relatives and Other Associates.</p>
<p>This means that the ASF website must not be used to make payments where a material benefit is received in return. For example, payments such as those listed below must be made direct to the club or organisation concerned:</p>
<ul><li>Membership or registration fees</li><li>Levies or other charges</li><li>Payments for travel or similar events</li></ul>
<h3>3. Donations and Grants</h3>
<p>We raise funds through donations and other means, for the development of sport (and in respect of ASFCF, where that is in in pursuit of a charitable purpose) and we make grants in accordance with that purpose. While we may have regard for your Preferred Sporting Cause you understand that we maintain discretion and control in accordance with legal obligations to pursue our purposes.</p>
<p>Where we receive a donation from you but have been provided with insufficient information to identify you or the Sporting Cause that the donation relates to, we will take reasonable steps to identify you and the Preferred Sporting Cause. If this information cannot be ascertained, we will hold the donation open for a period of 60 days to allow appropriate details to be provided. After 60 days, we will allocate the donation to another sporting cause at our discretion. Once a donation has been so allocated, it cannot be reallocated to another Preferred Sporting Cause, even if you and the Preferred Sporting Cause are later identified.</p>
<p>We also retain the right to withhold donations from a particular Preferred Sporting Cause or refuse to accept donations from a particular donor in our sole discretion and without giving reasons.</p>
<h3>4. Disclosure regarding donations and grants</h3>
<p>In line with our purpose of raising funds for the development of sport (and in respect of ASFCF, where that is in in pursuit of a charitable purpose), we aim at all times to maximise the amount of donated funds distributed by way of grants to Registered Sporting Projects and for the development of sport in Australia more broadly.</p>
<p>However, in common with all entities we have operating costs incurred in support of our activities, which include:</p>
<ul><li>Operating the improving the fundraising platform that is made available to all Fundraisers;</li><li>Providing support to Fundraisers through our Sports Fundraising Managers and Fundraising Support Team and through online tools and resources;</li><li>Advocating for sport as a philanthropic cause, and promoting the important benefits of sport to community health and cohesion; and</li><li>Managing regulatory compliance, including reviews by the Australian Taxation Office (ATO) in connection with tax deductible donations received.</li></ul>
<p>Costs in fulfilling these obligations must be met from donations received, and amounts distributed and retained are at our absolute discretion. However, in the interests of transparency we disclose that we distribute 95% of donated funds in the form of grants, and retain 5% to cover operating costs. These amounts may be varied at ASF Group’s discretion, and fundraisers and donors will be notified of any change at the appropriate time.</p>
<h3>5. Transactions fees and charges</h3>
<p>We incur charges from our financial providers for accepting donations by credit card and other means and these charges are passed on to you. As a result, we need to deduct a fee for donations of the following amounts:</p>
<table><tr><td>Payment Type</td><td>Fee per transaction</td></tr><tr><td>EFT</td><td>0.0%</td></tr><tr><td>Direct Debit</td><td>Up to $2.20</td></tr><tr><td>Mastercard / Visa</td><td>Between 1.0% to 1.55% + 15c</td></tr><tr><td>American Express</td><td>Between 1.55% to 2.0% + 15c</td></tr><tr><td>Apple Pay / Google Pay</td><td>1.55% + 15c</td></tr><tr><td>Regular Giving</td><td>Standard payment processing fee + 0.65%</td></tr></table>
<p>These charges may be varied from time to time.</p>
<p>*(1) The definition of associate (in section 78A of the Income Tax Assessment Act 1936 (Cth)) is very broad but includes blood relatives, companies which you and/or your associates control, partners in a partnership and spouses of those partners, as well as beneficiaries with an interest in a trust. This list is not exhaustive and is a guide only. Please refer to section 78A for the complete definition of associate relating to donations.</p>`;
